version: "3.8"
services:
  mysql:
    image: mysql:9.2
    ports:
      - "3306:3306"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: speed
      MYSQL_USER: speed
      MYSQL_PASSWORD: speed
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql.cnf:/etc/mysql/conf.d/my.cnf
      - ./logs:/var/log/mysql
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default


volumes:
  mysql-data:
