DROP USER IF EXISTS 'speed'@'%';


CREATE USER 'speed'@'%' IDENTIFIED BY 'speed';

GRANT ALL PRIVILEGES ON *.* TO 'speed'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS speed;
